# Generated by Django 4.0.3 on 2022-03-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
